import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { Providers } from "./providers";
import Navbar from "@/components/ui/Navbar";
import connectToDatabase from "@/lib/mongodb";
import Category, { ICategory } from "@/database/category.model";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "True Tea",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await connectToDatabase();
  const categories = (await Category.find({ active: true }).sort({
    catID: 1,
  })) as ICategory[];

  const serializedCategories = JSON.parse(JSON.stringify(categories));

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster position="top-center" />
        <Providers>
          <Navbar categories={serializedCategories} />
          {children}
        </Providers>
      </body>
    </html>
  );
}
